### ISSUE TITLE
`table.getn` is `nil`

### ISSUE THREAD

**Issue by ysimonson** [chucklefish/rlua#50]
Lua scripts executed from rlua do not seem to have a function `table.getn`. I would've thought that this line would ensure it's available: https://github.com/chucklefish/rlua/blob/master/src/lua.rs#L484

But it seems that while there's a global `table`, `table.getn` is `nil`. Is this expected?

Simplest way to reproduce this would be to run the repl example and run `table.getn({1,2})`.

**Comment by jonas-schievink** [comment]
getn was deprecated in Lua 5.1 and removed in 5.2, rlua currently only targets 5.3

If you really need it, perhaps there's a compatibility switch and you can compile your own Lua with it enabled

**Comment by ysimonson** [comment]
Ah, didn’t realize that. Thanks!
