### ISSUE TITLE
Panic if AnyUserData.get_user_value fails

### ISSUE THREAD

**Issue by psychon** [chucklefish/rlua#69]
```rust
extern crate rlua;

struct Unconvertible;

impl <'lua> rlua::FromLua<'lua> for Unconvertible {
    fn from_lua(_: rlua::Value<'lua>, _: &'lua rlua::Lua) -> rlua::Result<Self> {
        Err(rlua::Error::ExpiredUserData)
    }
}

struct MyData;

impl rlua::UserData for MyData {
}

fn main() {
    let lua = rlua::Lua::new();
    let data = lua.create_userdata(MyData).unwrap();
    data.get_user_value::<Unconvertible>().unwrap();
}
```
Output: (with `RUST_BACKTRACE=1`):
```
thread 'main' panicked at 'rlua internal error: expected stack to be 0, got 1', /home/psychon/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.12.0/src/util.rs:47:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rlua::util::stack_guard
             at ./<panic macros>:7
   8: rlua::userdata::AnyUserData::get_user_value
             at /home/psychon/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.12.0/src/userdata.rs:426
   9: rlua_test::main
             at src/main.rs:19
  10: __rust_maybe_catch_panic
  11: std::rt::lang_start
  12: main
  13: __libc_start_main
  14: _start
```
What I think happens:
This is the code for `get_user_value`:
```rust
    pub fn get_user_value<V: FromLua<'lua>>(&self) -> Result<V> {
        let lua = self.0.lua;
        unsafe {
            stack_guard(lua.state, 0, || {
                check_stack(lua.state, 2);
                lua.push_ref(lua.state, &self.0);
                ffi::lua_getuservalue(lua.state, -1);
                let res = V::from_lua(lua.pop_value(lua.state), lua)?;
                ffi::lua_pop(lua.state, 1);
                Ok(res)
            })
        }
    }
```
In the above, if `from_lua` fails, then the `lua_pop` is not executed and the `stack_guard` notices that something is wrong.

I have not really looked at the remaining code in rlua, but I guess that this problems also exists in other places. For example, I bet I could trigger a panic with `set_user_value` by making `to_lua` fail.

CC @Timidger

**Comment by kyren** [comment]
Oh, ugh, that's a very easy fix, it's supposed to be using "stack_err_guard" not "stack_guard".  That's what I get for incomplete tests.

**Comment by kyren** [comment]
Okay, that should be fixed in 7231e95195bad7eee5f049f431151b7d70756569.  Like I said the fix is easy, but the implication is troubling, because I have now at least messed up stack_guard vs stack_err_guard in two places and not caught it.

I checked every other place in the code that uses stack_guard for unexpectedly returning Err and didn't see anything, so hopefully that's it.

Maybe I should just get rid of stack_guard?  Maybe I should just write tests where a convertible type fails and call every single method with that type?

**Comment by kyren** [comment]
What happened was I had originally written `get_user_value` / `set_user_value` to just accept / return `Value`, but then realized that's stupid and changed them to accept `ToLua` / `FromLua` instead, but forgot to change the stack_guard to a stack_err_guard.

**Comment by psychon** [comment]
Thanks for the fix and really no need to explain yourself :-)
