### ISSUE TITLE
Exposing consuming methods in `UserDataMethods`?

### ISSUE THREAD

**Issue by ysimonson** [chucklefish/rlua#70]
Is it possible to expose a method that consumes `self` in `UserDataMethods`? The motivation is that I want to expose the [commit method of postgres connections](https://docs.rs/postgres/0.15.2/postgres/transaction/struct.Transaction.html#method.commit), however the typical `add_method`/`add_method_mut` won't work.

**Comment by kyren** [comment]
That seems be reasonable, now that invalidation is an accepted normal part of the API with ‘scope’.

However, the error message on access might not be great.  I can still add the feature, but in some cases it might be preferable to have the Userdata wrap an Option and return a custom error, and you can of course do that in the meantime.

**Comment by ysimonson** [comment]
Wouldn't that have the same issue? e.g. assuming I wrap the `Option<postgres::transaction::Transaction>` in a newtype since it's defined outside of the crate, and the method definition looked something like this:

```rust
methods.add_method_mut("commit", |_, this, ()| {
    if let Some(trans) = this.0 {
        trans.commit().map_err(|err| LuaError::RuntimeError(format!("{}", err)))
    } else {
        Err(LuaError::RuntimeError("The transaction has already finished".to_string()))
    }
});
```

I'd still get a `cannot move out of borrowed content` error.

**Comment by kyren** [comment]
You can use Option::take

**Comment by ysimonson** [comment]
Oh man, TIL. Thanks @kyren! This works great as-is; I'll just close this out.
