### ISSUE TITLE
Cannot reimplement luaL_tolstring / No accessible way for lua_topointer

### ISSUE THREAD

**Issue by psychon** [chucklefish/rlua#76]
Hi,

Lua's [default `tostring` implementation](https://github.com/chucklefish/rlua/blob/065c69894a08dc52e7a1baba9154681d6c0fa834/lua/lbaselib.c#L448) just calls `luaL_tolstring`. For `userdata`, `thread`s, ..., this [creates](https://github.com/chucklefish/rlua/blob/065c69894a08dc52e7a1baba9154681d6c0fa834/lua/lauxlib.c#L833-L840) a string of the form `[typename] [pointer]` where the pointer comes from `lua_topointer()`.

The current plan in [way-cooler](https://github.com/way-cooler/way-cooler) is to reimplement parts of [awesome](https://github.com/awesomeWM/awesome). Awesome [implements a similar `__tostring` metamethod](https://github.com/awesomeWM/awesome/blob/356d730b7df83178bbc6df55de4f550c4905a0c9/common/luaobject.c#L333-L368): This produces the name of the type (e.g. `button`) followed by the raw pointer. Right now I see no way to implement this with rlua. Taking the address of an `AnyUserData` (via `&foo as *const _`) does not work, since this just produces a "random pointer" to the stack.
(As I just learned when looking up the code, I could just add a `__name` field to the meta-table... interesting; thanks for making me solve my own problems! Still, I'll leave this paragraph in since it still might be nice to be able to implement this.)

The above might not be all that convincing (you could just tell me to "fake" a pointer, I guess), so here is another use case:
Awesome has objects called "tags". These are accessible outside of Lua (via X11). To make it possible for Lua to create (easy) and destroy (hard!) tags, tag objects have an `activated` property that can be set to true/false. When true, awesome uses `luaL_ref` to create a reference to the tag, saves it in a global list and makes it accessible externally.
I have [problems](https://github.com/way-cooler/way-cooler/issues/392#issuecomment-373978235) reimplementing this with rlua. My idea was to save a Table in the registry. When a tag becomes activated, I append the tag to the table (`table.set(table.len() + 1, object)`). However, when deactivating a tag, I have problems finding the right entry in the table. I do not want to use something like `PartialEq`, since that compares for equality, not object identity.
I do not have a really good reason for why I don't just do `table.set(object, true)` (i.e. using the object as key and let Lua figure out object identity) except for compatibility with awesome.

I think both of these problems could be fixed by providing wrappers for `lua_topointer` on `AnyUserData`, although I have to admit that this feels a bit hackish. Of course, I am always open for other suggestions as well. :-)

Edit: Well... okay, `__name` is not accessible through `UserDataMethods`, so that one does not help me either.

**Comment by Timidger** [comment]
Could this be solved by [borrow](https://docs.rs/rlua/0.13.0/rlua/struct.AnyUserData.html#method.borrow)ing the value (which requires knowing its type, which shouldn't be a big hurdle for us) and then getting a pointer to the inner value?

e.g:

```rust
let ref = user_data.borrow::<Tag>()?;
println!("Pointer is {:p}", &*ref as *const Tag);
```

**Comment by psychon** [comment]
Uhm... now I wonder what the problem was that made me conclude that the above does not work. However, I have no idea what that was....O.o
(Perhaps I got confused by the `get_object()` function in way-cooler since that clones the object...)

Sorry for the noise!

**Comment by kyren** [comment]
I'm glad you got it figured out!  I didn't know about `__name` before, and apparently it's used by some error reporting functions as well?  I might look into allowing that to be set on userdata metatables, but like everything else on userdata metatables it would probably be the same for all instances of a UserData.

**Comment by psychon** [comment]
> Could this be solved by borrowing the value (which requires knowing its type, which shouldn't be a big hurdle for us) and then getting a pointer to the inner value?

The short version: Yes, but I forgot to do a dereference (`*`) when testing. You apparently did not forget this. :-)

-----

Okay, I finally had the time to actually try this and... it does not work.
```rust
extern crate rlua;

use rlua::{Lua, AnyUserData, UserData, Result};

struct MyData();

impl UserData for MyData {}

fn run() -> Result<()> {
    let lua = Lua::new();
    lua.globals().set("object", MyData())?;

    let value = lua.globals().get::<_, AnyUserData>("object")?;
    println!("{:?}", &value.borrow::<MyData>()? as *const _);
    println!("{:?}", &value.borrow::<MyData>()? as *const _);
    println!("{:?}", &value.borrow::<MyData>()? as *const _);

    Ok(())
}

fn main() {
    run().unwrap()
}
```
Output (example):
```
0x7ffe4c9944d0
0x7ffe4c9946a0
0x7ffe4c994870
```
So apparently I already tried this, but forgot about the details when I closed this issue five days ago.

The return type of `borrow()` is `std::cell::Ref`, so what the code above actually prints is the address of this instance of `Ref`.
Instead, I need to do the following (note the extra `*`) so that `Ref` is dereferenced and I actually take the address of the contained object:
```
    println!("{:?}", &value.borrow::<MyData>()? as *const _);
```
...and with this modification, things actually start working.
