### ISSUE TITLE
Minor bug in guided tour

### ISSUE THREAD

**Issue by olson-dan** [chucklefish/rlua#78]
https://github.com/chucklefish/rlua/blob/71f3dd50a1f396ea2ff36462e3deb6a48a132c43/examples/guided_tour.rs#L145

This assert is missing an abs() call to make the `< EPSILON` comparison a valid substitution for equality.

As it stands, the function returning any magnitude lower than 5.0 will pass the assert correctly.

**Comment by kyren** [comment]
Yeah, that's wrong, derp.  Thanks for pointing that out!
