### ISSUE TITLE
LuaJIT support

### ISSUE THREAD

**Issue by berkus** [chucklefish/rlua#80]
Hi, found this note in lua-jit-sys crate:

```
Compatability with rlua and hlua

I will try to get rlua and hlua working
```

I wonder how much effort it is to add LuaJIT support to rlua? I found rlua has the most idiomatic and safe API to Lua out there, and it fits my needs almost perfectly - just need the LuaJIT there.

**Comment by jonas-schievink** [comment]
LuaJIT implements Lua 5.1, while rlua works with Lua 5.3. The C interface was also likely changed in ways that need fixes or conditional compilation. Currently, `rlua` uses the C interface pretty liberally all over the place, so this might get messy very quickly.

**Comment by berkus** [comment]
Ok, I see. Lets close this as a no, and I guess luajit is not planning to upgrade it's supported lua version either.
